//Ezren
export const SPELL_CHECK_TOP_CARD = "spell_check_top_card"
export const ACQUIRE_MAGIC_CARD = "acquire_magic_card"
export const ADD_TO_RECHARGE_CARD = "add_to_recharge_card"
export const EVOCATOR = "evocator"
export const ILLUSIONIST = "illusionist"
export const EVADE_MONSTER = "evade_monster"
export const ADD_ARCANE_CHECK = "arcane_check"
export const ADD_ARCANE_CHECK_ACID_COLD = "arcane_check_acid_cold"
export const ADD_ARCANE_CHECK_ELECTRIC_FIRE = "arcane_check_electric_fire"
export const BEGINNING_RECHARGE_CARD = "beginning_recharge_card"
export const ACQUIRE_SPELL = "acquire_spell"
export const ACQUIRE_SPELL_ALLY = "acquire_spell_ally"