version: "3.7"
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pathfinder
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
volumes:
  postgres:
